### ISSUE TITLE
Password Generator

### ISSUE THREAD

**Issue by ghost** [hasanbarary/pass_gen#1]
#1

> Good job. Now, we have a new challenge. Usually, these are not user-friendly. So, to solve this problem, we ask you to improve your code like bellow instructions.

1.  Get the username of the user 
2.  Validates username by length. ( e.g. The user must fill more than 5 characters and bellow than 14.
3.  Generate a password similar to that username.

For an instance, we have a username like sepehrak and generated password is $3PeH7^!c. Consider we have to generate 10 different passwords.

**It is an intelligent password generator.**

Are you as **genius** as we think?

**Comment by hasanbarary** [comment]
OK. Thanks

**Comment by hasanbarary** [comment]
1 and 2 done

**Comment by hasanbarary** [comment]
Issue complete
